# Generated by Django 3.0.8 on 2020-07-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20200630_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='url_interna',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
