# Generated by Django 3.0.8 on 2020-07-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_personamodel_url_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
