# Generated by Django 3.0.8 on 2020-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_personamodel_foto_de_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personamodel',
            name='url_interna',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='biografia',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='descripcion_emprendimiento',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
