# Generated by Django 3.0.8 on 2020-08-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20200807_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personamodel',
            old_name='fotos_productos',
            new_name='foto_producto1',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='foto_producto2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='foto_producto3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
